### ISSUE TITLE
类似 US01 和 SG02 的节点无法匹配（Clash/RemoteConfig/Lainbo.ini）

### ISSUE THREAD

**Issue by ShinkaiMakoto** [lainbo/gists-hub#2]
感谢您创建了如此全面且有用的规则

由于正则表达式中使用了 \b 单词边界，一些节点（例如 US01, SG02）无法匹配上

![image](https://github.com/user-attachments/assets/41c8cd55-224b-442f-9cfb-6c6bc1244cf6)

希望您能考虑修改。感谢您的辛勤工作！

**Comment by lainbo** [comment]
和\b没有关系，我写的是形如`\bJP[N]?(\d+)?\b`，也就是这样的效果
![image](https://github.com/user-attachments/assets/11880af4-9cf6-4012-8b0d-2541cfb5a65b)

你这里的问题是，后面的`0.20x`，我正则中的逻辑是不希望这些低倍率节点进入自动挡中，因为很多ai、需要付钱的网站，都有严格的风控机制，而这些低倍率节点往往有着很高的风控值，甚至是万人骑的ip，这不利于我们稳定的使用这些服务。

同时我也没有允许高倍率节点划入自动挡，因为很多人就是默认直接自动挡，那些高倍率节点往往有着更好的测速表现，容易被自动挡选中，这样很容易造成不经意间跑大量的流量

**Comment by ShinkaiMakoto** [comment]
了解 感谢耐心解答
