### ISSUE TITLE
telegram规则无法匹配

### ISSUE THREAD

**Issue by limy90** [lainbo/gists-hub#3]
大佬 首先感谢您编写的规则
在使用中发现tg无法匹配📲 Telegram规则 而是使用了🇪🇺 欧洲自动规则
不知道是否仅我自己出现了这个情况
期待您的回复

**Comment by lainbo** [comment]
匹配到欧洲的话，是因为这一行
https://github.com/lainbo/gists-hub/blob/master/src/Clash/RemoteConfig/Lainbo.ini/#L60

如果你的TG账号是DC2、DC4这两个区的，会优先使用欧洲的节点，DC1会自动走美国，DC5会自动走新加坡，保证速度最优

注册时使用的不同的手机号对应了你的tg数据的区域，[对应关系详见这里](https://t.me/KinhRoBotChannel/88)

你是因为没有欧洲节点，导致了自己DC2/DC4的账号无法联网是吗

**Comment by limy90** [comment]
查看了一下我的账号，是DC5的   也有新加坡节点，但走了西班牙节点
请问一下如果我想在手机上使用一个固定节点的话应该怎么操作

**Comment by lainbo** [comment]
可能是我没有表述清楚，
你在的号在DC5，DC5服务器位置位于**新加坡**，
接收小明的DC2账号，从**DC2服务器荷兰**发送过来的消息，

此时，你使用欧洲的节点，直接去接收消息（荷兰-欧洲节点-你本地），比新加坡节点（荷兰-新加坡-你本地）是要更快的，更不容易出现转圈圈转不出来。

也就是说如果DC2的发布者发布了一段视频，即使你的号在DC5，你也要访问荷兰数据中心来获取这段视频，所以这种情况下实际上使用欧洲节点会更快

你说的`我的账号，是DC5的 也有新加坡节点，但走了西班牙节点` ，原因就是你接收了来自DC2/DC4用户的信息

首先回答你的问题，
Q: 如何固定TG使用的节点？
A: 暂时没有方法，需要我这边修改一下规则，不再强制按TG的Data Center分流节点，这样Telegram那个策略组就会正常生效了

但是还有一个问题就是，我是否有必要这样做？
- 如果你说因为没有欧洲节点导致了功能异常，那我修改没有任何问题。
- 如果你说只是因为想要固定TG使用的节点（并不合理，有欧洲节点也不用），想这么做才提这个issue，那我觉得没有必要，因为当前的分流做法明显是优于固定节点的策略

**所以我想问一下，你是因为没有欧洲节点，导致了部分消息接收出现了问题吗**

**Comment by lainbo** [comment]
> 并没有因为节点问题导致消息接收出现问题，提出这个issue是因为之前我并不明白为什么没有走tg的策略，现在已经了解，所以问题已经得到解决 之所以想要使用固定节点是因为担心ip频繁变动导致账号被封禁（虽然说并不知道有没有这样的封禁原因） 最后，再次感谢您的解答 顺颂时祺

ip的变动不用担心的，详见[NodeSeek讨论](https://www.nodeseek.com/post-161459-3#22)
